name: Scrape data

on:
  workflow_dispatch:
  schedule:
    - cron: 0 12 * * *
jobs:
  scrape:
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v3
      - uses: mjguggen/covid-globe-scraper-action@v1
        with:
          mongo_uri: ${{ secrets.MONGO_URI }}
          github_token: ${{ secrets.GH_TOKEN }}
