name: Scrape data

on:
  workflow_dispatch:
  schedule:
    - cron: 0 12 * * *
jobs:
  scrape:
    runs-on: ubuntu-latest


    steps:
      - uses: mjguggen/covid-globe-scraper-action@v1.0.1
        with:
          mongo_uri: ${{ secrets.MONGO_URI }}
          token: ${{ secrets.GH_TOKEN }}
